plugins {
  id 'java'
  id 'org.springframework.boot' version '3.5.7'
  id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.gitbaby'
version = '0.0.1-SNAPSHOT'
description = 'happy_back'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

configurations {
  compileOnly {
    extendsFrom annotationProcessor
  }
  configureEach {
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
  // developmentOnly 'org.springframework.boot:spring-boot-devtools' // otel이랑 같이 사용 불가
  implementation 'org.springframework.boot:spring-boot-starter-mail:3.5.5'
  implementation 'org.springframework.boot:spring-boot-starter-validation'

  // otel
  implementation "io.opentelemetry:opentelemetry-api"
  implementation('io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.23.0')

  // db migration
  implementation 'org.flywaydb:flyway-core'
  implementation 'org.flywaydb:flyway-database-postgresql'

  // 암호화 해시
  implementation 'commons-codec:commons-codec:1.19.0'

  // 버전 비교용 라이브러리
  implementation 'org.apache.maven:maven-artifact:3.9.9'

  // 유저 접속 정보 파싱 라이브러리
  implementation 'com.github.ua-parser:uap-java:1.6.1'

  // Logging
  implementation 'org.springframework.boot:spring-boot-starter-log4j2'

  // Lombok
  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'
  testCompileOnly 'org.projectlombok:lombok'
  testAnnotationProcessor 'org.projectlombok:lombok'

  // MapStruct
  implementation 'org.mapstruct:mapstruct:1.6.3'
  annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
  annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

  // DB
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  runtimeOnly 'org.postgresql:postgresql'
  implementation 'org.springframework.boot:spring-boot-starter-data-redis'
  implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

  // JWT
  implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
  runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
  runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

  // AWS SDK
  implementation platform("software.amazon.awssdk:bom:2.25.39")
  implementation "software.amazon.awssdk:s3"
  implementation "software.amazon.awssdk:sts"

  // swagger
  implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'

  // Test
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
  useJUnitPlatform()
}

bootRun {

    jvmArgs = [
        // OpenTelemetry Java Agent 로드
        "-javaagent:${projectDir}/infra/otel/opentelemetry-javaagent.jar",

        // 서비스 이름
        "-Dotel.service.name=happygivers",

        // OTLP Exporter 엔드포인트
        "-Dotel.exporter.otlp.endpoint=http://localhost:4318",

        // OTLP 전송 프로토콜
        "-Dotel.exporter.otlp.protocol=http/protobuf",

        // 샘플러 전략(부모 span 따라가기)
        "-Dotel.traces.sampler=parentbased_traceidratio",

        // 샘플링 비율 (0.5 = 50%)
        "-Dotel.traces.sampler.arg=1",

        // 로그, 메트릭 전송 비활성화
        "-Dotel.logs.exporter=none",
        "-Dotel.metrics.exporter=none"

    ]
}

