spring:
  config:
    import:
      - optional:classpath:secret/prod/redis.yml
      - optional:classpath:secret/prod/cookie.yml
      - optional:classpath:secret/prod/oauth.yml
      - optional:classpath:secret/prod/db.yml
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.springframework.security: error
custom:
  api-url: "https://api.happy.gitbaby.com"
  frontend-url: "https://happygivers.gitbaby.com"
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
