spring:
  application:
    name: happy_back
  flyway:
    enabled: true
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:secret/jwt.yml
      - optional:classpath:secret/mail.yml
