spring:
  config:
    import:
      - optional:classpath:secret/dev/redis.yml
      - optional:classpath:secret/dev/cookie.yml
      - optional:classpath:secret/dev/oauth.yml
      - optional:classpath:secret/dev/db.yml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        hibernate.generate_statistics: true
    show_sql: true
logging:
  level:
    org.springframework.security: DEBUG
custom:
  api-url: "http://localhost:8080"
  frontend-url: "http://localhost:3000"
