spring:
  config:
    import:
      - optional:classpath:secret/prod/redis.yml
      - optional:classpath:secret/prod/cookie.yml
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.security: error
custom:
  api-url: "https://api.happy.gitbaby.com"
  frontend-url: "https://happy.gitbaby.com"
