# OTEL_COLLECTOR_CONFIG=./collector-dev.yml docker-compose up

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  filter/drop_hikari_housekeeper:
    spans:
      exclude:
        match_type: regexp
        attributes:
          - key: thread.name
            value: "HikariPool.*:housekeeper"
  batch: {}

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - filter/drop_hikari_housekeeper
        - batch
      exporters: [otlp]
